---


- name: Download docker installer shell script
  get_url: 
    url: https://get.docker.com  
    dest: /tmp/get_docker.sh

- name: Execute the /tmp/get_docker.sh
    shell: /tmp/get_docker.sh


#    name: ['docker-ce','docker-ce-cli','containerd.io']
#    state: present
#
#- name: Install Docker-compose
#  get_url:
#    url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
#    dest: /usr/local/bin/docker-compose
#
