---

- debug:
    mesg: {{ansible_distribution|lower}} {{ansible_distribution_release}}

- name: Add Docker APT repository
  yum_repository:
    name: docker
    description: docker repo
    file: docker
    baseurl: https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}}
    gpgcheck: https://download.docker.com/linux/centos/gpg

#- name: Install Docker packages
#  yum:
#    name: ['docker-ce','docker-ce-cli','containerd.io']
#    state: present
#
#- name: Install Docker-compose
#  get_url:
#    url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
#    dest: /usr/local/bin/docker-compose
#
