---


- name: Add Docker YUM repository, this will work for centos,fedora,opensuse or oraclelinux 
  yum_repository:
    name: docker
    description: docker repository
    file: docker
    baseurl: https://yum.dockerproject.org/repo/main/{{ansible_distribution|lower}}/{{ansible_distribution_major_version}}/
    gpgcheck: no

- name: Install Docker packages
  yum:
    name: 
     - docker-engine
    state: present

- name: Start service httpd, if not started
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
    dest: /usr/local/bin/docker-compose
    mode: 0522
#
